# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

before_script:
  - hostname
  - whoami
  - pwd
  - ls -la
  - docker --version

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - coverage

build:
  tags:
     - ece651
  stage: build
  script: docker build --build-arg LOCAL_USER_ID=`id -u`  --tag citest .

test:
  tags:
     - ece651
  stage: test
  script: scripts/run-tests-in-docker.sh
  coverage: '/TOTAL COVERAGE: \d+(?:\.\d+)?/'
  artifacts:
    paths:
      - coverage

pages:
 stage: coverage
 tags:
     - ece651
 dependencies:
   - test
 script:
   - scripts/run-javadoc-in-docker.sh
   - mv coverage public/
   - mv javadoc public/
 artifacts:
   paths:
     - public

