/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.projectTeam8;

import java.io.IOException;
import java.net.ServerSocket;

public class App {
    private AcademicEnrollment academicEnrollment;
    private static final int PORT = 5000;


    

    public App(AcademicEnrollment academicEnrollment) {
        this.academicEnrollment = academicEnrollment;
    }

    public static void main(String[] args) {
        
        try{
            AcademicEnrollment academicEnrollment = new DatabaseAcademicEnrollment(new MySQLDatabase());
            App app = new App(academicEnrollment);
            ServerSocket serverSocket = new ServerSocket(PORT);
            ClientHandlerFactory clientHandlerFactory = new DefaultClientHandlerFactory();
            Server server = new Server(serverSocket,clientHandlerFactory, academicEnrollment);   
            server.startServer();
            
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Exception thrown: " + e.getMessage());
        } finally {
            System.out.println("Server is stopped");
        
        }

    }
}


